### ISSUE TITLE
ES6 compatibility issue

### ISSUE THREAD

**Issue by PranavPillai** [decentraland/dappeteer#2]
I have a create react app. Normally running npm test runs all of our test specs properly, but when I add the file from your readme as a test file, this is the error that i get:

` FAIL  src/test/E2ETestingSuite.spec.js
  ● Test suite failed to run

    /Users/pranavpillai/Consensys/ujo-portal/ujo-portal/node_modules/dappeteer/index.js:7
      launch: async function launch (puppeteer, options = {}) {
                    ^^^^^^^^

    SyntaxError: Unexpected token function

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:289:17)
      at Object.<anonymous> (src/test/E2ETestingSuite.spec.js:20:180)`

It seems like we’re facing an ES6 compilation error. Do you have to configure your jest in any way to preprocess code in the node modules?

**Comment by cazala** [comment]
Hi @PranavPillai, you are probably using node < 8, can you check by running `node -v`?

This package needs node v8+

I just created a new app with `create-react-app` and dropped this file inside `src`

**E2EApp.test.js**

```js
import puppeteer from 'puppeteer'
import dappeteer from 'dappeteer'

jasmine.DEFAULT_TIMEOUT_INTERVAL = 200000

it('test dappeteer in CRA', async () => {
  const browser = await dappeteer.launch(puppeteer)
  const metamask = await dappeteer.getMetamask(browser)

  // import MetaMask account
  await metamask.importAccount(
    'already turtle birth enroll since owner keep patch skirt drift any dinner'
  )

  // switch to Ropsten
  await metamask.switchNetwork('ropsten')

  // open decentraland marketplace settings
  const marketplace = await browser.newPage()
  await marketplace.goto('https://market.decentraland.org/settings')

  // click "agree" on ToS
  await marketplace.waitForSelector('.get-started button.primary')
  const agreeButton = await marketplace.$('.get-started button.primary')
  await agreeButton.click()

  // Authorize marketplace contract
  await marketplace.waitForSelector('input[type="checkbox"]')
  const checkbox = (await marketplace.$$('input[type="checkbox"]'))[0]
  await checkbox.click()

  // submit tx
  await metamask.confirmTransaction()

  // wait for tx to start
  await marketplace.bringToFront()
  await marketplace.waitForSelector('.TxStatusText')

  // wait for tx to be mined
  await marketplace.waitFor(
    () => document.querySelector('.TxStatusText') == null,
    {
      timeout: 180000
    }
  )

  // close browser
  await browser.close()
})
```

And I did `npm test` and both `App.test.js` and `E2EApp.test.js` both run just fine.

**Comment by PranavPillai** [comment]
You were right; thanks!
