### ISSUE TITLE
Support headless mode

### ISSUE THREAD

**Issue by kivutar** [decentraland/dappeteer#4]
Headless mode allows to run puppeteer tests in travis.

But dappeteer is not working properly in headless mode.

For example, all the `page.waitForSelector` time out.

**Comment by fvictorio** [comment]
As far as I know, you can't install extensions in headless chrome. Travis has [a section](https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-xvfb-to-run-tests-that-require-a-gui) on using `xvfb` that might work, though.

**Comment by kivutar** [comment]
You're right
